CREATE TABLE QrOpens (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  Codigo VARCHAR(20) NOT NULL,
  Nombre NVARCHAR(200) NOT NULL,
  Ciudad VARCHAR(50) NOT NULL,
  OpenedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UserAgent NVARCHAR(500) NULL
);

CREATE INDEX IX_QrOpens_Codigo_Date ON QrOpens (Codigo, OpenedAt);
